name: Build and Deploy
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          conda-channels: anaconda
          
      - name: Install required dependencies
        run: |
          conda install -c conda-forge graph-tool
          pip install Sphinx
          pip install clingo
          python3 setup.py install
          pip install sphinx-copybutton
          pip install furo
          pip install wheel
          pip install twine
